language: go

sudo: false

go:
  - 1.7
  - 1.8
  - tip

matrix:
  allow_failures:
    - go: tip

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic .
  - go test -run='$none' -bench=.

after_success:
  - bash <(curl -s https://codecov.io/bash)
