language: go

sudo: false

go:
  - 1.7
  - 1.8
  - tip

matrix:
  allow_failures:
    - go: tip

script:
  - bash test.sh
  - go test -run='$none' -benchmem -bench=. $(go list ./... | grep -v /vendor/)

after_success:
  - bash <(curl -s https://codecov.io/bash)
